M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu20.04.1} date Mi 02 Aug 2023 00:09:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-02T00:09:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X123.5Y-83.5
X123.5Y-106.5
X181.5Y-83.5
X181.5Y-106.5
T0
M30
